### ISSUE TITLE
no such option: --per_sink_feature_assignments

### ISSUE THREAD

**Issue by chloelulu** [biota/sourcetracker2#101]
Hi, 

I got the error when running `sourcetracker2 gibbs -i otu_table.biom -m map.txt -o example7/ --per_sink_feature_assignments`.
I install the st2 based on the github mentioned conda install procedure. 
And `sourcetracker2 --version
sourcetracker2, version 2.0.1`
May I know what is the reason? 
Thanks.

**Comment by wdwvt1** [comment]
Hi Lu,

Unfortunately, the latest version of ST2 available on pip doesn't have the
--per_sink_feature_assignments functionality. You can upgrade to the
development version which does have that feature. To do that:

source activate st2
git clone https://github.com/biota/sourcetracker2.git
cd sourcetracker2
python setup.py install

Then you should be able to use that option.

Best,
Will

**Comment by chloelulu** [comment]
Hi, @wdwvt1 ,

Cool! It works very well! Millions of thanks.

**Comment by chloelulu** [comment]
Hi, @wdwvt1 ,

Sorry. After running for a while, I got the error. >^<
May I know how to fix this? Thanks so much.

Traceback (most recent call last): File "/Users/guest/anaconda/envs/st2/bin/sourcetracker2", line 11, in <module> load_entry_point('sourcetracker==2.0.1.dev0', 'console_scripts', 'sourcetracker2')() File "/Users/guest/anaconda/envs/st2/lib/python3.5/site-packages/click/core.py", line 722, in __call__ return self.main(*args, **kwargs) File "/Users/guest/anaconda/envs/st2/lib/python3.5/site-packages/click/core.py", line 697, in main rv = self.invoke(ctx) File "/Users/guest/anaconda/envs/st2/lib/python3.5/site-packages/click/core.py", line 1066, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) File "/Users/guest/anaconda/envs/st2/lib/python3.5/site-packages/click/core.py", line 895, in invoke return ctx.invoke(self.callback, **ctx.params) File "/Users/guest/anaconda/envs/st2/lib/python3.5/site-packages/click/core.py", line 535, in invoke return callback(*args, **kwargs) File "/Users/guest/anaconda/envs/st2/lib/python3.5/site-packages/sourcetracker-2.0.1.dev0-py3.5.egg/sourcetracker/_cli/gibbs.py", line 233, in gibbs_cli File "/Users/guest/anaconda/envs/st2/lib/python3.5/site-packages/sourcetracker-2.0.1.dev0-py3.5.egg/sourcetracker/_sourcetracker.py", line 801, in gibbs File "<decorator-gen-136>", line 2, in map File "/Users/guest/anaconda/envs/st2/lib/python3.5/site-packages/ipyparallel/client/view.py", line 52, in sync_results ret = f(self, *args, **kwargs) File "/Users/guest/anaconda/envs/st2/lib/python3.5/site-packages/ipyparallel/client/view.py", line 623, in map return pf.map(*sequences) File "/Users/guest/anaconda/envs/st2/lib/python3.5/site-packages/ipyparallel/client/remotefunction.py", line 299, in map return self(*sequences, __ipp_mapping=True) File "<decorator-gen-126>", line 2, in __call__ File "/Users/guest/anaconda/envs/st2/lib/python3.5/site-packages/ipyparallel/client/remotefunction.py", line 80, in sync_view_results return f(self, *args, **kwargs) File "/Users/guest/anaconda/envs/st2/lib/python3.5/site-packages/ipyparallel/client/remotefunction.py", line 285, in __call__ return r.get() File "/Users/guest/anaconda/envs/st2/lib/python3.5/site-packages/ipyparallel/client/asyncresult.py", line 169, in get raise self.exception() File "/Users/guest/anaconda/envs/st2/lib/python3.5/site-packages/ipyparallel/client/asyncresult.py", line 228, in _resolve_result results = error.collect_exceptions(results, self._fname) File "/Users/guest/anaconda/envs/st2/lib/python3.5/site-packages/ipyparallel/error.py", line 233, in collect_exceptions raise e File "/Users/guest/anaconda/envs/st2/lib/python3.5/site-packages/ipyparallel/error.py", line 231, in collect_exceptions raise CompositeError(msg, elist) ipyparallel.error.CompositeError: one or more exceptions from call to method: functools.partial(<function gibbs_sampler at 0x110d84d90>, draws_per_restart=1, burnin=100, restarts=10, cp=<sourcetracker._sourcetracker.ConditionalProbability object at 0x1105e94e0>, delay=1) [0:apply]: NameError: name 'generate_environment_assignments' is not defined [1:apply]: NameError: name 'generate_environment_assignments' is not defined [2:apply]: NameError: name 'generate_environment_assignments' is not defined [3:apply]: NameError: name 'generate_environment_assignments' is not defined .... 1 more exceptions ...
