### ISSUE TITLE
ValueError: Mapping file or biom table passed contain no `source` samples

### ISSUE THREAD

**Issue by sjschuld** [biota/sourcetracker2#113]
I installed st2 yesterday and successfully ran all tiny-test examples. When attempting to use my own data and the method "Calculate the proportion of each source in each sink" I received the error below. Any help in resolving would be greatly appreciated. 

Traceback (most recent call last):
  File "/anaconda3/envs/st2/bin/sourcetracker2", line 11, in <module>
    sys.exit(cli())
  File "/anaconda3/envs/st2/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/anaconda3/envs/st2/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/anaconda3/envs/st2/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/anaconda3/envs/st2/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/anaconda3/envs/st2/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/anaconda3/envs/st2/lib/python3.5/site-packages/sourcetracker/_cli/gibbs.py", line 168, in gibbs
    raise ValueError('Mapping file or biom table passed contain no '
ValueError: Mapping file or biom table passed contain no `source` samples

**Comment by johnchase** [comment]
Closing issue with no recent activity
