### ISSUE TITLE
Issue with SourceTracker2 installation

### ISSUE THREAD

**Issue by lizdasa** [biota/sourcetracker2#136]
Hello, 

I am trying to install sourcetracker in a cluster computer and I am getting an error after I test if my installation was successful. 

What I did:

> conda create -n sourcetracker2 -c biocore python=3.5 numpy scipy scikit-bio biom-format h5py hdf5 seaborn
> conda activate sourcetracker2
> conda install -c bioconda sourcetracker
> sourcetracker2 gibbs --help             ****after this I get the following error:

Traceback (most recent call last):
  File "/storage/home/hcoda1/6/ldavila3/.conda/envs/sourcetracker2/bin/sourcetracker2", line 6, in <module>
    from sourcetracker._cli import cli
  File "/storage/home/hcoda1/6/ldavila3/.conda/envs/sourcetracker2/lib/python3.5/site-packages/sourcetracker/_cli/__init__.py", line 19, in <module>
    import_module('sourcetracker._cli.gibbs')
  File "/storage/home/hcoda1/6/ldavila3/.conda/envs/sourcetracker2/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/storage/home/hcoda1/6/ldavila3/.conda/envs/sourcetracker2/lib/python3.5/site-packages/sourcetracker/_cli/gibbs.py", line 23, in <module>
    from sourcetracker._sourcetracker import (
  File "/storage/home/hcoda1/6/ldavila3/.conda/envs/sourcetracker2/lib/python3.5/site-packages/sourcetracker/_sourcetracker.py", line 15, in <module>
    from skbio.stats import subsample_counts
  File "/storage/home/hcoda1/6/ldavila3/.conda/envs/sourcetracker2/lib/python3.5/site-packages/skbio/__init__.py", line 13, in <module>
    import skbio.io  # noqa
  File "/storage/home/hcoda1/6/ldavila3/.conda/envs/sourcetracker2/lib/python3.5/site-packages/skbio/io/__init__.py", line 238, in <module>
    import_module('skbio.io.format.lsmat')
  File "/storage/home/hcoda1/6/ldavila3/.conda/envs/sourcetracker2/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/storage/home/hcoda1/6/ldavila3/.conda/envs/sourcetracker2/lib/python3.5/site-packages/skbio/io/format/lsmat.py", line 77, in <module>
    from skbio.stats.distance import DissimilarityMatrix, DistanceMatrix
  File "/storage/home/hcoda1/6/ldavila3/.conda/envs/sourcetracker2/lib/python3.5/site-packages/skbio/stats/distance/__init__.py", line 192, in <module>
    from ._base import (DissimilarityMatrixError, DistanceMatrixError,
  File "/storage/home/hcoda1/6/ldavila3/.conda/envs/sourcetracker2/lib/python3.5/site-packages/skbio/stats/distance/_base.py", line 13, in <module>
    from IPython.core.pylabtools import print_figure
  File "/storage/home/hcoda1/6/ldavila3/.conda/envs/sourcetracker2/lib/python3.5/site-packages/IPython/__init__.py", line 55, in <module>
    from .terminal.embed import embed
  File "/storage/home/hcoda1/6/ldavila3/.conda/envs/sourcetracker2/lib/python3.5/site-packages/IPython/terminal/embed.py", line 16, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "/storage/home/hcoda1/6/ldavila3/.conda/envs/sourcetracker2/lib/python3.5/site-packages/IPython/terminal/interactiveshell.py", line 32, in <module>
    from .debugger import TerminalPdb, Pdb
  File "/storage/home/hcoda1/6/ldavila3/.conda/envs/sourcetracker2/lib/python3.5/site-packages/IPython/terminal/debugger.py", line 6, in <module>
    from IPython.core.completer import IPCompleter
  File "/storage/home/hcoda1/6/ldavila3/.conda/envs/sourcetracker2/lib/python3.5/site-packages/IPython/core/completer.py", line 146, in <module>
    import jedi
  File "/storage/home/hcoda1/6/ldavila3/.conda/envs/sourcetracker2/lib/python3.5/site-packages/jedi/__init__.py", line 41, in <module>
    from jedi.api import Script, Interpreter, set_debug_function, \
  File "/storage/home/hcoda1/6/ldavila3/.conda/envs/sourcetracker2/lib/python3.5/site-packages/jedi/api/__init__.py", line 15, in <module>
    import parso
  File "/storage/home/hcoda1/6/ldavila3/.conda/envs/sourcetracker2/lib/python3.5/site-packages/parso/__init__.py", line 41, in <module>
    from parso.parser import ParserSyntaxError
  File "/storage/home/hcoda1/6/ldavila3/.conda/envs/sourcetracker2/lib/python3.5/site-packages/parso/parser.py", line 113
    node_map: Dict[str, type] = {}
            ^
SyntaxError: invalid syntax

I'll appreciate any help!

**Comment by celinecuinat** [comment]
Hi Lizdasa,
I am getting the same error, did you manage to solve this issue? Thanks for any help!

**Comment by claireewilliams** [comment]
@celinecuinat I ran into a different error and used python=3.6 instead of 3.5 because it appears there are some compatibility issues between the packages. Not sure if that would solve your error, but thought I'd mention it!

**Comment by tuttigiuperterra** [comment]
I'm having the exact same problem! 
Does anyone know how to solution it?

**Comment by tuttigiuperterra** [comment]
When installing from git (pip uninstall sourcetracker && pip install git+https://github.com/biota/sourcetracker2.git)
the same command works!!!

**Comment by howyim** [comment]
I encountered the same problem using Python 3.5.6 after running this:

> sourcetracker2 gibbs --help

Traceback (most recent call last):
  File "/srv/scratch/z3520673/bin/miniconda3/envs/st2/bin/sourcetracker2", line 5, in <module>
    from sourcetracker._cli.gibbs import gibbs
  File "/srv/scratch/z3520673/bin/miniconda3/envs/st2/lib/python3.5/site-packages/sourcetracker/__init__.py", line 11, in <module>
    from ._sourcetracker import gibbs
  File "/srv/scratch/z3520673/bin/miniconda3/envs/st2/lib/python3.5/site-packages/sourcetracker/_sourcetracker.py", line 17, in <module>
    from skbio.stats import subsample_counts
  File "/srv/scratch/z3520673/bin/miniconda3/envs/st2/lib/python3.5/site-packages/skbio/__init__.py", line 13, in <module>
    import skbio.io  # noqa
  File "/srv/scratch/z3520673/bin/miniconda3/envs/st2/lib/python3.5/site-packages/skbio/io/__init__.py", line 238, in <module>
    import_module('skbio.io.format.lsmat')
  File "/srv/scratch/z3520673/bin/miniconda3/envs/st2/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/srv/scratch/z3520673/bin/miniconda3/envs/st2/lib/python3.5/site-packages/skbio/io/format/lsmat.py", line 77, in <module>
    from skbio.stats.distance import DissimilarityMatrix, DistanceMatrix
  File "/srv/scratch/z3520673/bin/miniconda3/envs/st2/lib/python3.5/site-packages/skbio/stats/distance/__init__.py", line 192, in <module>
    from ._base import (DissimilarityMatrixError, DistanceMatrixError,
  File "/srv/scratch/z3520673/bin/miniconda3/envs/st2/lib/python3.5/site-packages/skbio/stats/distance/_base.py", line 13, in <module>
    from IPython.core.pylabtools import print_figure
  File "/srv/scratch/z3520673/bin/miniconda3/envs/st2/lib/python3.5/site-packages/IPython/__init__.py", line 55, in <module>
    from .terminal.embed import embed
  File "/srv/scratch/z3520673/bin/miniconda3/envs/st2/lib/python3.5/site-packages/IPython/terminal/embed.py", line 16, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "/srv/scratch/z3520673/bin/miniconda3/envs/st2/lib/python3.5/site-packages/IPython/terminal/interactiveshell.py", line 32, in <module>
    from .debugger import TerminalPdb, Pdb
  File "/srv/scratch/z3520673/bin/miniconda3/envs/st2/lib/python3.5/site-packages/IPython/terminal/debugger.py", line 6, in <module>
    from IPython.core.completer import IPCompleter
  File "/srv/scratch/z3520673/bin/miniconda3/envs/st2/lib/python3.5/site-packages/IPython/core/completer.py", line 146, in <module>
    import jedi
  File "/srv/scratch/z3520673/bin/miniconda3/envs/st2/lib/python3.5/site-packages/jedi/__init__.py", line 41, in <module>
    from jedi.api import Script, Interpreter, set_debug_function, \
  File "/srv/scratch/z3520673/bin/miniconda3/envs/st2/lib/python3.5/site-packages/jedi/api/__init__.py", line 15, in <module>
    import parso
  File "/srv/scratch/z3520673/bin/miniconda3/envs/st2/lib/python3.5/site-packages/parso/__init__.py", line 41, in <module>
    from parso.parser import ParserSyntaxError
  File "/srv/scratch/z3520673/bin/miniconda3/envs/st2/lib/python3.5/site-packages/parso/parser.py", line 113
    node_map: Dict[str, type] = {}
            ^
SyntaxError: invalid syntax

Any solution?
