### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by tuttigiuperterra** [biota/sourcetracker2#144]
I've installed source tracker with Conda.
Then I run this command:

> sourcetracker2 gibbs -i metagenome_OTU.txt -m map.txt -o output/ 

I did receive this error message and no output: 

Traceback (most recent call last):
  File "/Users/bioinfo/opt/anaconda3/envs/sourcetracker2/bin/sourcetracker2", line 6, in <module>
    from sourcetracker._cli import cli
  File "/Users/bioinfo/opt/anaconda3/envs/sourcetracker2/lib/python3.5/site-packages/sourcetracker/_cli/__init__.py", line 19, in <module>
    import_module('sourcetracker._cli.gibbs')
  File "/Users/bioinfo/opt/anaconda3/envs/sourcetracker2/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/bioinfo/opt/anaconda3/envs/sourcetracker2/lib/python3.5/site-packages/sourcetracker/_cli/gibbs.py", line 23, in <module>
    from sourcetracker._sourcetracker import (
  File "/Users/bioinfo/opt/anaconda3/envs/sourcetracker2/lib/python3.5/site-packages/sourcetracker/_sourcetracker.py", line 15, in <module>
    from skbio.stats import subsample_counts
  File "/Users/bioinfo/opt/anaconda3/envs/sourcetracker2/lib/python3.5/site-packages/skbio/__init__.py", line 13, in <module>
    import skbio.io  # noqa
  File "/Users/bioinfo/opt/anaconda3/envs/sourcetracker2/lib/python3.5/site-packages/skbio/io/__init__.py", line 238, in <module>
    import_module('skbio.io.format.lsmat')
  File "/Users/bioinfo/opt/anaconda3/envs/sourcetracker2/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/bioinfo/opt/anaconda3/envs/sourcetracker2/lib/python3.5/site-packages/skbio/io/format/lsmat.py", line 77, in <module>
    from skbio.stats.distance import DissimilarityMatrix, DistanceMatrix
  File "/Users/bioinfo/opt/anaconda3/envs/sourcetracker2/lib/python3.5/site-packages/skbio/stats/distance/__init__.py", line 192, in <module>
    from ._base import (DissimilarityMatrixError, DistanceMatrixError,
  File "/Users/bioinfo/opt/anaconda3/envs/sourcetracker2/lib/python3.5/site-packages/skbio/stats/distance/_base.py", line 13, in <module>
    from IPython.core.pylabtools import print_figure
  File "/Users/bioinfo/opt/anaconda3/envs/sourcetracker2/lib/python3.5/site-packages/IPython/__init__.py", line 55, in <module>
    from .terminal.embed import embed
  File "/Users/bioinfo/opt/anaconda3/envs/sourcetracker2/lib/python3.5/site-packages/IPython/terminal/embed.py", line 16, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "/Users/bioinfo/opt/anaconda3/envs/sourcetracker2/lib/python3.5/site-packages/IPython/terminal/interactiveshell.py", line 18, in <module>
    from prompt_toolkit.enums import DEFAULT_BUFFER, EditingMode
  File "/Users/bioinfo/opt/anaconda3/envs/sourcetracker2/lib/python3.5/site-packages/prompt_toolkit/__init__.py", line 16, in <module>
    from .application import Application
  File "/Users/bioinfo/opt/anaconda3/envs/sourcetracker2/lib/python3.5/site-packages/prompt_toolkit/application/__init__.py", line 1, in <module>
    from .application import Application
  File "/Users/bioinfo/opt/anaconda3/envs/sourcetracker2/lib/python3.5/site-packages/prompt_toolkit/application/application.py", line 255
    self.full_screen: bool = full_screen
                    ^
SyntaxError: invalid syntax

What should I do?

**Comment by vfonti** [comment]
I've just realized I had got an error message because of cython, which I had not installed. If you fixed that, it should work.
