### ISSUE TITLE
Error when trying to run ST2. 

### ISSUE THREAD

**Issue by mawij2002** [biota/sourcetracker2#94]
Hi,

The previous version (installed as indicated in the README) worked but it did not have the per_feature_assignment option. I have installed the most recent (as indicated in another issue thread (https://github.com/biota/sourcetracker2/issues/85). The thing is that with the new one install I cannot make it work. It gives me an error (copied below). Can you guys help me out? Thanks!

JP.

/Users/jm44736-mac/miniconda2/envs/st2/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/Users/jm44736-mac/miniconda2/envs/st2/bin/sourcetracker2", line 11, in <module>
    load_entry_point('sourcetracker==2.0.1.dev0', 'console_scripts', 'sourcetracker2')()
  File "/Users/jm44736-mac/miniconda2/envs/st2/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jm44736-mac/miniconda2/envs/st2/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/jm44736-mac/miniconda2/envs/st2/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jm44736-mac/miniconda2/envs/st2/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jm44736-mac/miniconda2/envs/st2/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/jm44736-mac/miniconda2/envs/st2/lib/python3.5/site-packages/sourcetracker/_cli/gibbs.py", line 161, in gibbs_cli
    intersect_and_sort_samples(sample_metadata, feature_table)
  File "/Users/jm44736-mac/miniconda2/envs/st2/lib/python3.5/site-packages/sourcetracker/_sourcetracker.py", line 127, in intersect_and_sort_samples
    shared_samples = np.intersect1d(sample_metadata.index, feature_table.index)
  File "/Users/jm44736-mac/miniconda2/envs/st2/lib/python3.5/site-packages/numpy/lib/arraysetops.py", line 334, in intersect1d
    ar1 = unique(ar1)
  File "/Users/jm44736-mac/miniconda2/envs/st2/lib/python3.5/site-packages/numpy/lib/arraysetops.py", line 210, in unique
    return _unique1d(ar, return_index, return_inverse, return_counts)
  File "/Users/jm44736-mac/miniconda2/envs/st2/lib/python3.5/site-packages/numpy/lib/arraysetops.py", line 277, in _unique1d
    ar.sort()
TypeError: unorderable types: float() < str()

@gregcaporaso @wdwvt1

**Comment by lkursell** [comment]
Hi @mawij2002 - that TypeError suggests that we should check the formatting of your input files. Can you check that the values in the OTU table are stored as integers, and not as strings?
